name: Django CI/CD

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install django djangorestframework drf-yasg
      working-directory: aiServer

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Debug Environment Variables
      run: |
        echo "EC2_HOST: $EC2_HOST"
        echo "EC2_USER: $EC2_USER"
        echo "$EC2_KEY" > key.pem
        chmod 400 key.pem
        ls -al key.pem

    - name: Upload Code to EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ubuntu
        EC2_KEY: ${{ secrets.EC2_KEY }}
      run: |
        scp -o StrictHostKeyChecking=no -i key.pem -r ./aiServer ubuntu@$EC2_HOST:/home/ubuntu/

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem -t ubuntu@$EC2_HOST << 'EOF'
        cd /home/ubuntu/aiServer
        python3 -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install django djangorestframework drf-yasg
        nohup gunicorn --bind 0.0.0.0:8000 aiServer.wsgi:application &
        sudo service nginx restart
        EOF

    - name: Clean up
      run: rm key.pem
