name: Django CI/CD

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install django djangorestframework drf-yasg
      working-directory: aiServer

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Upload and Deploy Code to EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ubuntu
        EC2_KEY: ${{ secrets.EC2_KEY }}
        SECRET: ${{ secrets.SECRETS }}
      run: |
        echo "${{ secrets.EC2_KEY }}" > key.pem
        chmod 400 key.pem
        # secrets.json 파일 생성
        ssh -o StrictHostKeyChecking=no -i key.pem $EC2_USER@$EC2_HOST << EOF
          echo '{"SECRET_KEY": "'"${SECRET}"'"}' > /home/ubuntu/aiServer/secrets.json
        EOF
        
        # 코드 업로드
        scp -o StrictHostKeyChecking=no -i key.pem -r ./aiServer $EC2_USER@$EC2_HOST:/home/ubuntu/
        
        # 서버에 접속하여 작업 수행
        ssh -o StrictHostKeyChecking=no -i key.pem $EC2_USER@$EC2_HOST << EOF
          cd /home/ubuntu/aiServer || exit 1
          python3 -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install setuptools corsheaders django djangorestframework drf-yasg gunicorn
          nohup gunicorn --bind 0.0.0.0:8000 aiServer.wsgi:application &
          sudo service nginx restart
        EOF
        
        # 사용된 키 삭제
        rm key.pem
